traefik:
  deployment:
    # -- Deployment or DaemonSet
    kind: Deployment
    # -- Number of pods of the deployment (only applies when kind == Deployment)
    replicas: 3

  podDisruptionBudget:
    enabled: true
    minAvailable: 1

  ingressClass:
    isDefaultClass: true

  core:  # @schema additionalProperties: false

  experimental:
    kubernetesGateway:
      # -- Enable traefik experimental GatewayClass CRD
      enabled: false

  gateway:
    # -- When providers.kubernetesGateway.enabled, deploy a default gateway
    enabled: false

  gatewayClass:  # @schema additionalProperties: false
    # -- When providers.kubernetesGateway.enabled and gateway.enabled, deploy a default gatewayClass
    enabled: false

  api:
    dashboard: false
    # -- Enable the insecure API (HTTP)
    #insecure:  # @schema type:[boolean, null]
    insecure: false
    # -- Enable the debug API
    #debug:  # @schema type:[boolean, null]
    # -- Configure API basePath
    #basePath: ""  # @schema type:[string, null]; default: "/"

  # -- Only dashboard & healthcheck IngressRoute are supported.
  # It's recommended to create workloads CR outside of this Chart.
  # @default -- See _values.yaml_
  # I prefer ingress for cert-manager => I will do it outside
  ingressRoute:
    dashboard:
      # -- Create an IngressRoute for the dashboard
      enabled: false
      # -- The router match rule used for the dashboard ingressRoute
      # matchRule: PathPrefix(`/dashboard`) || PathPrefix(`/api`)
      # host must be manually created in DNS because it points to internal service, not a service exposed
      matchRule: Host(`traefik.pci.proserv.ovh`)
      # -- Additional ingressRoute middlewares (e.g. for authentication)
      middlewares:
        - name: "http-basic"
      entryPoints:
        - websecure
      tls:
        secretName: traefik-dashboard-tls
      # for external-dns: do a CNAME on test, but can be the IP of the LB for A
      annotations:
        external-dns.alpha.kubernetes.io/target: "51.178.114.225"

    healthcheck:
      # -- Create an IngressRoute for the healthcheck probe
      enabled: false

  # @schema additionalProperties: false
  providers:
    # @schema additionalProperties: false
    kubernetesCRD:
      # -- Load Kubernetes IngressRoute provider
      enabled: true

    # @schema additionalProperties: false
    kubernetesIngress:
      # -- Load Kubernetes Ingress provider
      enabled: true

    # @schema additionalProperties: false
    kubernetesGateway:
      # -- Enable Traefik Gateway provider for Gateway API
      enabled: false

    # @schema additionalProperties: false
    file:
      # -- Create a file provider
      enabled: false

    # @schema additionalProperties: false
    kubernetesIngressNginx:
      # -- Enable Kubernetes Ingress NGINX provider (experimental)
      enabled: false

    # @schema additionalProperties: false
    knative:
      # -- Enable Knative provider
      enabled: false

  logs:
    general:
      # -- Set [logs format](https://doc.traefik.io/traefik/observability/logs/#format)
      format:  # @schema enum:["common", "json", null]; type:[string, null]; default: "common"
      # By default, the level is set to INFO.
      # -- Alternative logging levels are TRACE, DEBUG, INFO, WARN, ERROR, FATAL, and PANIC.
      level: "INFO"  # @schema enum:[TRACE,DEBUG,INFO,WARN,ERROR,FATAL,PANIC]; default: "INFO"
      otlp:
        # -- Set to true in order to enable OpenTelemetry on logs. Note that experimental.otlpLogs needs to be enabled.
        enabled: false

    access:
      # -- To enable access logs
      enabled: false
      # -- Set [access log format](https://doc.traefik.io/traefik/observability/access-logs/#format)
      format:  # @schema enum:["common", "genericCLF", "json", null]; type:[string, null]; default: "common"
      otlp:
        # -- Set to true in order to enable OpenTelemetry on access logs. Note that experimental.otlpLogs needs to be enabled.
        enabled: false

  metrics:
    # -- Enable metrics for internal resources. Default: false
    addInternals: false

    ## Prometheus is enabled by default.
    ## It can be disabled by setting "prometheus: null"
    prometheus: null
    # prometheus:
    #   # -- Entry point used to expose metrics.
    #   entryPoint: metrics
    #   # -- Enable metrics on entry points. Default: true
    #   addEntryPointsLabels: true
    #   # -- Enable metrics on routers. Default: false
    #   # set to true to get metrics per ingress
    #   addRoutersLabels: true
    #   # -- Enable metrics on services. Default: true
    #   addServicesLabels: true
    #   # -- Buckets for latency metrics. Default="0.1,0.3,1.2,5.0"
    #   serviceMonitor:
    #     # -- Enable optional CR for Prometheus Operator. See EXAMPLES.md for more details.
    #     enabled: true
    #     apiVersion: "monitoring.coreos.com/v1"
    #     metricRelabelings: []
    #     relabelings: []
    #     jobLabel: ""
    #     interval: ""
    #     honorLabels: false
    #     scrapeTimeout: ""
    #     honorTimestamps: false
    #     enableHttp2: false
    #     followRedirects: false
    #     additionalLabels:
    #       release: prometheus
    #     namespace: ""
    #     namespaceSelector: {}
    #   prometheusRule:
    #     # -- Enable optional CR for Prometheus Operator. See EXAMPLES.md for more details.
    #     enabled: false
    #     apiVersion: "monitoring.coreos.com/v1"
    #     additionalLabels:
    #       release: prometheus
    #     namespace: ""
    #     rules: []

    otlp:
      # -- Set to true in order to enable the OpenTelemetry metrics
      enabled: false

  ocsp:
    # -- Enable OCSP stapling support.
    # See https://doc.traefik.io/traefik/https/ocsp/#overview
    enabled: false

  ## Tracing
  # -- https://doc.traefik.io/traefik/observability/tracing/overview/
  # @default -- See _values.yaml_
  tracing:  # @schema additionalProperties: false
    # -- Enables tracing for internal resources. Default: false.
    addInternals: false

  global:
    checkNewVersion: true
    # -- Please take time to consider whether or not you wish to share anonymous data with us
    # See https://doc.traefik.io/traefik/contributing/data-collection/
    sendAnonymousUsage: false

  ports:
    web:
      forwardedHeaders:
        # -- Trust forwarded headers information (X-Forwarded-*).
        trustedIPs: []
        insecure: false

    websecure:
      http:
        tls:
          # -- See [upstream documentation](https://doc.traefik.io/traefik/reference/install-configuration/entrypoints/#opt-http-tls)
          # @default -- true
          enabled: true
          options: ""
          certResolver: ""
          domains: []
        # force HSTS for all traffic
        middlewares:
          - traefik-hsts@kubernetescrd
      http3:
        ## -- Enable HTTP/3 on the entrypoint
        ## Enabling it will also enable http3 experimental feature
        ## https://doc.traefik.io/traefik/routing/entrypoints/#http3
        ## There are known limitations when trying to listen on same ports for
        ## TCP & UDP (Http3). There is a workaround in this chart using dual Service.
        ## https://github.com/kubernetes/kubernetes/issues/47249#issuecomment-587960741
        enabled: false
        advertisedPort:  # @schema type:[integer, null]; minimum:0
      forwardedHeaders:
          # -- Trust forwarded headers information (X-Forwarded-*).
        trustedIPs: []
        insecure: false

  service:
    enabled: true
    ## -- Single service is using `MixedProtocolLBService` feature gate.
    ## -- When set to false, it will create two Service, one for TCP and one for UDP.
    single: true
    type: LoadBalancer
    # -- Additional annotations applied to both TCP and UDP services (e.g. for cloud provider specific config)
    annotations:
      # keep floating IP: will not be deleted if service is deleted
      loadbalancer.openstack.org/keep-floatingip: "true"
      # for proxy protocol
      # be careful, it will apply for all pools
      # if you need ingressroutetcp for instance (for ssh gitlab for instance), it will not work
      # loadbalancer.openstack.org/proxy-protocol: "v2"
    # -- Additional annotations for TCP service only
    annotationsTCP: {}
    # -- Additional annotations for UDP service only
    annotationsUDP: {}
    spec:
      #externalTrafficPolicy: Cluster
      # to enable proxy protocol, set Local
      # externalTrafficPolicy: Local
      # to reuse an existing floating IP
      # loadBalancerIP: "xx.xx.xx.xx"
      # clusterIP: "2.3.4.5"

  autoscaling:  # @schema additionalProperties: false
    # -- Create HorizontalPodAutoscaler object.
    # See EXAMPLES.md for more details.
    enabled: false

  persistence:
    # -- Enable persistence using Persistent Volume Claims
    # ref: http://kubernetes.io/docs/user-guide/persistent-volumes/.
    # It can be used to store TLS certificates along with `certificatesResolvers.<name>.acme.storage`  option
    enabled: false

  # -- Enable to create a PodSecurityPolicy and assign it to the Service Account via RoleBinding or ClusterRoleBinding
  podSecurityPolicy:
    enabled: false

  # -- [Resources](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/) for `traefik` container.
  resources: {}

  # -- This example pod anti-affinity forces the scheduler to put traefik pods
  # -- on nodes where no other traefik pods are scheduled.
  # It should be used when hostNetwork: true to prevent port conflicts
  affinity: {}
  #  podAntiAffinity:
  #    requiredDuringSchedulingIgnoredDuringExecution:
  #      - labelSelector:
  #          matchLabels:
  #            app.kubernetes.io/name: '{{ template "traefik.name" . }}'
  #            app.kubernetes.io/instance: '{{ .Release.Name }}-{{ include "traefik.namespace" . }}'
  #        topologyKey: kubernetes.io/hostname

  # -- nodeSelector is the simplest recommended form of node selection constraint.
  nodeSelector: {}
  # -- Tolerations allow the scheduler to schedule pods with matching taints.
  tolerations: []
  # -- You can use topology spread constraints to control
  # how Pods are spread across your cluster among failure-domains.
  topologySpreadConstraints:
   - labelSelector:
       matchLabels:
         app.kubernetes.io/name: '{{ template "traefik.name" . }}'
     matchLabelKeys:
     - pod-template-hash
     topologyKey: topology.kubernetes.io/zone
     maxSkew: 1
     whenUnsatisfiable: ScheduleAnyway
   - labelSelector:
       matchLabels:
         app.kubernetes.io/name: '{{ template "traefik.name" . }}'
     matchLabelKeys:
     - pod-template-hash
     topologyKey: kubernetes.io/hostname
     maxSkew: 1
     whenUnsatisfiable: ScheduleAnyway

  # -- Additional arguments to be passed at Traefik's binary
  # See [CLI Reference](https://docs.traefik.io/reference/static-configuration/cli/)
  # Use curly braces to pass values: `helm install --set="additionalArguments={--providers.kubernetesingress.ingressclass=traefik-internal,--log.level=DEBUG}"`
  additionalArguments:
    - --entryPoints.web.http.redirections.entryPoint.to=:443
    - --entryPoints.web.http.redirections.entryPoint.scheme=https
    - --entryPoints.web.http.redirections.entryPoint.permanent=true
    - --entryPoints.web.observability.accessLogs=false
    - --entryPoints.web.observability.metrics=false
    - --entryPoints.web.observability.tracing=false
  #  - "--providers.kubernetesingress.ingressclass=traefik-internal"
  #  - "--log.level=DEBUG"
