apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: test-external-secret
  namespace: default
spec:
  refreshInterval: 1h0m0s

  secretStoreRef:
    name: cluster-store
    kind: ClusterSecretStore

  target:
    name: test-external-secret
    creationPolicy: Owner

  data:
    - secretKey: toto
      remoteRef:
        key: test
        property: key

