argo-cd:
  ## Global
  global:
    # -- Default domain used by all components
    ## Used for ingresses, certificates, SSO, notifications, etc.
    domain: argo-cd.esante.gouv.fr

  ## Controller
  controller:

    # -- The number of application controller pods to run.
    # If changing the number of replicas you must pass the number as `ARGOCD_CONTROLLER_REPLICAS` as an environment variable
    replicas: 1

    resources:
    #  limits:
    #    cpu: 500m
    #    memory: 512Mi
      requests:
        cpu: 1000m
        memory: 512Mi

    metrics:
      # -- Deploy metrics service
      enabled: true
      serviceMonitor:
        # -- Enable a prometheus ServiceMonitor
        enabled: true
        # -- Prometheus ServiceMonitor interval
        interval: 180s
        # -- Prometheus [RelabelConfigs] to apply to samples before scraping
        relabelings: []
        # -- Prometheus [MetricRelabelConfigs] to apply to samples before ingestion
        metricRelabelings: []
        # -- Prometheus ServiceMonitor selector
        selector: {}
          # prometheus: kube-prometheus

        # -- Prometheus ServiceMonitor scheme
        scheme: ""
        # -- Prometheus ServiceMonitor tlsConfig
        tlsConfig: {}
        # -- Prometheus ServiceMonitor namespace
        namespace: "" # "prometheus"
        # -- Prometheus ServiceMonitor labels
        additionalLabels:
          release: prometheus
        # -- Prometheus ServiceMonitor annotations
        annotations: {}
      rules:
        # -- Deploy a PrometheusRule for the application controller
        enabled: true
        # -- PrometheusRule namespace
        namespace: "" # "prometheus"
        # -- PrometheusRule selector
        selector: {}
          # prometheus: kube-prometheus

        # -- PrometheusRule labels
        additionalLabels:
          release: prometheus
        # -- PrometheusRule annotations
        annotations: {}

        # -- PrometheusRule.Spec for the application controller
        spec:
        - alert: ArgoAppMissing
          expr: |
            absent(argocd_app_info) == 1
          for: 15m
          labels:
            severity: critical
          annotations:
            summary: "[Argo CD] No reported applications"
            description: >
              Argo CD has not reported any applications data for the past 15 minutes which
              means that it must be down or not functioning properly.  This needs to be
              resolved for this app to continue to maintain state.
        - alert: ArgoAppNotSynced
          expr: |
            argocd_app_info{sync_status="OutOfSync"} == 1
          for: 30m
          labels:
            severity: warning
          annotations:
            summary: "One or more Argo CD applications are not synchronized"
            description: >
              The application {{$labels.name}} has not been synchronized for over
              15 minutes which means that the state of this app has drifted away from the
              state inside Git.
        - alert: ArgoAppUnknown
          expr: |
            argocd_app_info{sync_status="Unknown"} == 1
          for: 30m
          labels:
            severity: warning
          annotations:
            summary: "One or more Argo CD applications are in 'unknown' status"
            description: >
              The application {{$labels.name}} is in 'unknown' status for over
              15 minutes which means that the state of this app is maybe not synced.
              This can happen when vault has been restarted and waiting for unseal keys.
        - alert: ArgocdServiceUnhealthy
          expr: |
            argocd_app_info{health_status!="Healthy"} != 0
          for: 30m
          labels:
            severity: warning
          annotations:
            summary: "One or more Argo CD applications are unhealthy"
            description: >
              The application {{$labels.name}} is unhealthy for over 15 minutes, which means
              that the application may not work properly.

  ## Dex
  dex:
    # -- Enable dex
    enabled: false

  ## Server
  server:
    replicas: 1

    # -- Additional command line arguments to pass to Argo CD server
    extraArgs:
      # - --insecure: use configs.params.server.insecure instead
      - --enable-gzip

    ingress:
      # -- Enable an ingress resource for the Argo CD server
      enabled: true
      # -- Defines which ingress controller will implement the resource
      ingressClassName: "traefik"
      # -- Additional ingress annotations
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"

      # -- Argo CD server hostname
      # @default -- `""` (defaults to global.domain)
      # hostname: ""

      # -- The path to Argo CD server
      path: /

      # -- Ingress path type. One of `Exact`, `Prefix` or `ImplementationSpecific`
      pathType: Prefix

      # -- Enable TLS configuration for the hostname defined at `server.ingress.hostname`
      ## TLS certificate will be retrieved from a TLS secret `argocd-server-tls`
      ## You can create this secret via `certificate` or `certificateSecret` option
      tls: true


    # dedicated ingress for gRPC as documented at
    # Ref: https://argo-cd.readthedocs.io/en/stable/operator-manual/ingress/
    ingressGrpc:
      # -- Enable an ingress resource for the Argo CD server for dedicated [gRPC-ingress]
      enabled: false

    resources:
    #  limits:
    #    cpu: 100m
    #    memory: 128Mi
      requests:
        cpu: 500m
        memory: 256Mi

    ## Server metrics service configuration
    metrics:
      # -- Deploy metrics service
      enabled: true
      serviceMonitor:
        # -- Enable a prometheus ServiceMonitor
        enabled: true
        # -- Prometheus ServiceMonitor interval
        interval: 30s
        # -- Prometheus [RelabelConfigs] to apply to samples before scraping
        relabelings: []
        # -- Prometheus [MetricRelabelConfigs] to apply to samples before ingestion
        metricRelabelings: []
        # -- Prometheus ServiceMonitor selector
        selector: {}
          # prometheus: kube-prometheus

        # -- Prometheus ServiceMonitor scheme
        scheme: ""
        # -- Prometheus ServiceMonitor tlsConfig
        tlsConfig: {}
        # -- Prometheus ServiceMonitor namespace
        namespace: ""  # prometheus
        # -- Prometheus ServiceMonitor labels
        additionalLabels:
          release: prometheus
        # -- Prometheus ServiceMonitor annotations
        annotations: {}

  ## Repo Server
  repoServer:

    replicas: 1

    resources:
    #  limits:
    #    cpu: 50m
    #    memory: 128Mi
      requests:
        cpu: 500m
        memory: 256Mi

    ## Repo server metrics service configuration
    metrics:
      # -- Deploy metrics service
      enabled: true
      serviceMonitor:
        # -- Enable a prometheus ServiceMonitor
        enabled: true
        # -- Prometheus ServiceMonitor interval
        interval: 30s
        # -- Prometheus [RelabelConfigs] to apply to samples before scraping
        relabelings: []
        # -- Prometheus [MetricRelabelConfigs] to apply to samples before ingestion
        metricRelabelings: []
        # -- Prometheus ServiceMonitor selector
        selector: {}
          # prometheus: kube-prometheus

        # -- Prometheus ServiceMonitor scheme
        scheme: ""
        # -- Prometheus ServiceMonitor tlsConfig
        tlsConfig: {}
        # -- Prometheus ServiceMonitor namespace
        namespace: "" # "prometheus"
        # -- Prometheus ServiceMonitor labels
        additionalLabels:
          release: prometheus
        # -- Prometheus ServiceMonitor annotations
        annotations: {}


  applicationSet:
    # -- The number of controller pods to run
    replicas: 1

    resources:
      # limits:
      #   cpu: 100m
      #   memory: 128Mi
       requests:
         cpu: 200m
         memory: 128Mi

  ## Argo Configs
  configs:

    # General Argo CD configuration
    ## Ref: https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/argocd-cm.yaml
    cm:

      statusbadge.enabled: true
      admin.enabled: true

      # -- Enable exec feature in Argo UI
      ## Ref: https://argo-cd.readthedocs.io/en/latest/operator-manual/rbac/#exec-resource
      exec.enabled: true

      # Application reconciliation timeout is the max amount of time required to discover if a new manifests version got
      # published to the repository. Reconciliation by timeout is disabled if timeout is set to 0. Three minutes by default.
      timeout.reconciliation: "120s"
      # Timeout to refresh application data as well as target manifests cache
      timeout.hard.reconciliation: "1800s"

      # exclude velero backups as they are created by velero schedules and must not be managed by argoCD
      resource.exclusions: |
        - apiGroups:
          - "velero.io"
          kinds:
          - Backup
          clusters:
          - "*"
        # add all from default values
        - apiGroups:
          - ''
          - discovery.k8s.io
          kinds:
          - Endpoints
          - EndpointSlice
        ### Internal Kubernetes resources excluded reduce the number of watched events
        - apiGroups:
          - coordination.k8s.io
          kinds:
          - Lease
        ### Internal Kubernetes Authz/Authn resources excluded reduce the number of watched events
        - apiGroups:
          - authentication.k8s.io
          - authorization.k8s.io
          kinds:
          - SelfSubjectReview
          - TokenReview
          - LocalSubjectAccessReview
          - SelfSubjectAccessReview
          - SelfSubjectRulesReview
          - SubjectAccessReview
        ### Intermediate Certificate Request excluded reduce the number of watched events
        - apiGroups:
          - certificates.k8s.io
          kinds:
          - CertificateSigningRequest
        - apiGroups:
          - cert-manager.io
          kinds:
          - CertificateRequest
        ### Cilium internal resources excluded reduce the number of watched events and UI Clutter
        - apiGroups:
          - cilium.io
          kinds:
          - CiliumIdentity
          - CiliumEndpoint
          - CiliumEndpointSlice
        ### Kyverno intermediate and reporting resources excluded reduce the number of watched events and improve performance
        - apiGroups:
          - kyverno.io
          - reports.kyverno.io
          - wgpolicyk8s.io
          kinds:
          - PolicyReport
          - ClusterPolicyReport
          - EphemeralReport
          - ClusterEphemeralReport
          - AdmissionReport
          - ClusterAdmissionReport
          - BackgroundScanReport
          - ClusterBackgroundScanReport
          - UpdateRequest

    # Argo CD configuration parameters
    ## Ref: https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/argocd-cmd-params-cm.yaml
    params:
      # -- Run server without TLS
      ## NOTE: This value should be set when you generate params by other means as it changes ports used by ingress template.
      server.insecure: true

      # log level for reposerver
      reposerver.log.level: debug
      # reposerver.log.level: trace


    # Argo CD sensitive data
    # Ref: https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/#sensitive-data-and-sso-client-secrets
    secret:
      # -- Bcrypt hashed admin password
      ## Argo expects the password in the secret to be bcrypt hashed. You can create this hash with
      ## `htpasswd -nbBC 10 "" $ARGO_PWD | tr -d ':\n' | sed 's/$2y/$2a/'`
      argocdServerAdminPassword: "$2a$10$Wnt4l8QhfuEd.6zFF5oO4.ozQvbOl3x/cNg3dFA0ZH1s6bWP1ziui"
      # -- Admin password modification time. Eg. `"2006-01-02T15:04:05Z"`
      # @default -- `""` (defaults to current time)
      argocdServerAdminPasswordMtime: "2026-07-17T00:00:00Z"

    # SSH known hosts for Git repositories
    ## Ref: https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#ssh-known-host-public-keys
    ssh:

      # -- Specifies if the argocd-ssh-known-hosts-cm configmap should be created by Helm.
      create: true

      # -- Additional known hosts for private repositories
      #extraHosts:
        # gitlab
        #gitlab.mondomain.com ecdsa-sha2-nistp256 XXXXXXXX

    # -- Repository credentials to be used as Templates for other repos
    ## Creates a secret for each key/value specified below to create repository credentials
    #credentialTemplates:
    #ssh-creds:
    #url: ssh://git@gitlab.mondomain.com/xxxxxx
    #sshPrivateKey: |
    #-----BEGIN OPENSSH PRIVATE KEY-----
    #     XXXXXXX
    #     -----END OPENSSH PRIVATE KEY-----
    repositories:
      git-helm:
        name: dsi-argo-cd-deploiement-cluster
        type: git
        ### attention : dans le cas de github, ne pas mettre le ssh:// sinon ca ne marche pas !
        ### same same avec gitlab et la notation : git@gitlab.mondomain.com:administration/helm.git
        url: git@github.com:ansforge/DSI-argo-cd-deploiement-cluster.git

  redis:
    # -- Enable redis
    enabled: true

    resources:
    #  limits:
    #    cpu: 200m
    #    memory: 128Mi
      requests:
        cpu: 200m
        memory: 128Mi
    metrics:
      # -- Deploy metrics service
      enabled: true

      serviceMonitor:
        # -- Enable a prometheus ServiceMonitor
        enabled: true
        # -- Interval at which metrics should be scraped
        interval: 30s
        # -- Prometheus [RelabelConfigs] to apply to samples before scraping
        relabelings: []
        # -- Prometheus [MetricRelabelConfigs] to apply to samples before ingestion
        metricRelabelings: []
        # -- Prometheus ServiceMonitor selector
        selector: {}
          # prometheus: kube-prometheus

        # -- Prometheus ServiceMonitor scheme
        scheme: ""
        # -- Prometheus ServiceMonitor tlsConfig
        tlsConfig: {}
        # -- Prometheus ServiceMonitor namespace
        namespace: "" # "prometheus"
        # -- Prometheus ServiceMonitor labels
        additionalLabels:
          release: prometheus
        # -- Prometheus ServiceMonitor annotations
        annotations: {}
    ## Prometheus redis-exporter sidecar
    exporter:
      # -- Enable Prometheus redis-exporter sidecar
      enabled: true
      # -- Resource limits and requests for redis-exporter sidecar
      resources:
        # limits:
        #   cpu: 50m
        #   memory: 64Mi
        # requests:
        #   cpu: 10m
        #   memory: 32Mi
        requests:
          cpu: 100m
          memory: 64Mi

  notifications:
    # -- Enable Notifications controller
    enabled: false


