apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-argo-external-secret
spec:
  refreshInterval: 1h0m0s

  secretStoreRef:
    name: cluster-store
    kind: ClusterSecretStore

  target:
    name: github-argo-secret
    creationPolicy: Owner
    template: 
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repo-creds

  data:
    - secretKey: sshPrivateKey
      remoteRef:
        key: github_argocd
        property: private_key_64
        decodingStrategy: Base64
    - secretKey: url
      remoteRef:
        key: github_argocd
        property: url
