cert-manager:
  crds:
    enabled: true

  resources: {}
    # requests:
    #   cpu: 10m
    #   memory: 32Mi

  webhook:
    resources: {}
      # requests:
      #   cpu: 10m
      #   memory: 32Mi

  cainjector:
    resources: {}
      # requests:
      #   cpu: 10m
      #   memory: 32Mi

  startupapicheck:
    resources: {}
      # requests:
      #   cpu: 10m
      #   memory: 32Mi

  prometheus:
    enabled: true
    servicemonitor:
      enabled: true
      prometheusInstance: default
      interval: 60s
      scrapeTimeout: 30s
      annotations: {}
      labels:
        release: prometheus
      honorLabels: false
      endpointAdditionalProperties: {}

   
