apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-registry-external-secret
spec:
  refreshInterval: 1h0m0s

  secretStoreRef:
    name: cluster-store
    kind: ClusterSecretStore

  target:
    name: secretharborregistry
    creationPolicy: Owner

  data:
    - secretKey: .dockerconfigjson
      remoteRef:
        key: harbor-registry
        property: dockerconfigjson

