apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rag-si-samu-external-secret
spec:
  refreshInterval: 1h0m0s

  secretStoreRef:
    name: cluster-store
    kind: ClusterSecretStore

  target:
    name: rag-si-samu-secret
    creationPolicy: Owner

  data:
    - secretKey: AUTH_CLIENT_ID
      remoteRef:
        key: rag-si-samu
        property: AUTH_CLIENT_ID
    - secretKey: AUTH_CLIENT_SECRET
      remoteRef:
        key: rag-si-samu
        property: AUTH_CLIENT_SECRET
    - secretKey: AUTH_URL
      remoteRef:
        key: rag-si-samu
        property: AUTH_URL
    - secretKey: AUTH_SECRET
      remoteRef:
        key: rag-si-samu
        property: AUTH_SECRET
